name: bioiain
channels:
  - defaults
  - conda-forge
  - bioconda
dependencies:
  - pip
  - python=3.12
  - foldseek
  - pymol-open-source
  - pip:
    - numpy==1.26.4
    - biopython==1.86
    - pandas==3.0.0
    - matplotlib==3.10.8
    - scikit-learn==1.8.0
    - scipy==1.17.0
    - setuptools>=80.10.1
    - typing-extensions>=4.15.0
    - requests>=2.32.5
    - unidecode>=1.4.0
    - xmltodict>=0.14.2