[build-system]
requires = [
    "setuptools >= 77.0.3",
    "biopython >= 1.85",
    "pandas >= 2.2.3",
    "numpy >= 2.2.5",
    "matplotlib >= 3.10.7",
    "typing-extensions >= 4.15.0",
    "requests >= 2.32.5",
    "unidecode >= 1.4.0"
]
build-backend = "setuptools.build_meta"


[project]
name = "bioiain"
version = "0.0.3"
authors = [
  { name="Iain Visa", email="iainvisa@gmail.com" },
]
description = "Package for structural analysis of proteins"
readme = "README.md"
requires-python = ">=3.13"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]
license = "MIT"
license-files = ["LICEN[CS]E*"]

[project.urls]
Homepage = "https://github.com/Thecnopapa/bioiain"
Issues = "https://github.com/Thecnopapa/bioiain/issues"